### PR TITLE
Allow checking a binary filter without deserializing to a resource

### PR DESCRIPTION
**Pull request by Vagabond**

### CODE REVIEW

**Comment by mpope9** [comment]
at first glance it looks like the resource usage of contain wouldn't work, but I could just be mistaken.  I will take another look later in the week and give it a run.  This addition is much appreciated.

**Comment by Vagabond** [comment]
It checks if its a resource, if it's not a resource it checks if its a binary and tries to populate the xor filter struct/fingerprints from the values in the binary. This definitely *does* work as I've done quite a lot of benchmarking with it.

**Comment by mpope9** [comment]
My mistake, my cursory glace was wrong!

**Comment by Vagabond** [comment]
Any updates on this?

**Comment by mpope9** [comment]
My mistake, have been distracted recently.

**Pull request merged**
