### PR TITLE
Add to_bin and from_bin serialization/deserialization

### PR DESCRIPTION
**Pull request by Vagabond**
One of the key advantages of xor filters is they are small and
immutable. This means sending them over the wire or storing them on
disk or in a database is a very useful usecase. This patch adds support
for serializing/deserializing xor8 and xor16 filters to and from an
Erlang binary to make storing/transferring xor filters easy.

### CODE REVIEW

**Comment by mpope9** [comment]
Huge fan of this.  Will take a closer look in a few days and merge this.

**Comment by Vagabond** [comment]
Yeah, I'd like to have a broader discussion of this, especially around endianess. It would be nice to have the filter be truly portable, etc.

I'm also experimenting with a change that allows contain() to take a serialized binary filter and it will decode to a xor filter on the stack, check it and return the result. This is good if I want to avoid any allocations (my use case is checking a big linear list of filters stored in rocksdb).

I also have a branch that contains both of my PRs merged together if that makes things easier from a merge perspective (I wanted to break them up in case you had objections to one but not the other).

**Comment by mpope9** [comment]
Yeah, a separate contain would make sense.  I think an interface that looks like this will make sense:
```
Filter = xor8(),
SerializedFilter = xor8:to_bin(Filter),
true = xor8:contain(SerialzedFilter, key).
```
Would make sense, where `to_bin` returns `{bin, serialized}` or something similar.  That might be a bit messy, but its my first thought as a nice interface, easier for the user if they don't need to marshal the filter to see if it contains something.

Two PRs is fine with me.  Easier to read them forsure.

**Comment by mpope9** [comment]
Strange issue when trying to pull this branch, I've added your repo as a remote and when I attempt to fetch I get:
```
fatal: repository 'https://github.com/Vagabond/exor_filter/tree/adt/serialization/' not found
```

which is unfortunate.  I'd like to run this before merging just in case :)

**Comment by mpope9** [comment]
Removed the remote and readded it, now fetching works.  Must have messed something up...giving this a run now.

**Comment by mpope9** [comment]
I think a better solution would be for the `to_bin` to return a
```
{FilterBinary, HashingMethod}
```
instead, and have the `from_bin` just return the second argument un-touched.  Then the user application can keep track of the hashing method or do a mapping to make sure whatever downstream using the xor_filter (erlang or not) can make the equivalent hashing decisions through some mapping.  Is this too cumbersome for your needs?  I think its more consistent with the current API, too.  I'd make these changes but I am unsure if I can push them up to your branch.

Also, there are two dialyzer warnings, but I can fix those after this is merged.

**Comment by Vagabond** [comment]
Now you've merged #8 I can rework this patch and make the requested changes. After that I can submit a PR for the `check without de-serializing` optimization.

**Comment by Vagabond** [comment]
Ok, I think I've made the requested changes. Let me know if there's anything else you'd like me to adjust.

**Comment by Vagabond** [comment]
Here's the patch that allows `contain` to work with serialized filters:

https://github.com/mpope9/exor_filter/commit/b36f3f58c10f2c33229709449c1fc60536191d4c

I can't make a PR for it unless you want me to add it to this branch, or until you merge this PR.

**Comment by mpope9** [comment]
Sweet looks good.

**Pull request merged**
